import {StyleSheet} from 'react-native'

import {shadows, themeColors} from '@/global/theme'

export const styles = StyleSheet.create({
    card: {
        borderRadius: 22,
        backgroundColor: themeColors.surface,
        paddingTop: 16,
        paddingBottom: 12,
        paddingHorizontal: 14,
        overflow: 'hidden',
        ...shadows.lg,
    },
    accentEdge: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        end: 0,
        width: 4,
        backgroundColor: themeColors.tertiary,
        opacity: 0.95,
    },
    row: {flexDirection: 'row', alignItems: 'center'},
    logoBox: {
        width: 56,
        height: 56,
        borderRadius: 16,
        backgroundColor: themeColors.primaryContainer,
        justifyContent: 'center',
        alignItems: 'center',
        marginEnd: 12,
    },
    logo: {width: 36, height: 36},
    info: {flex: 1, marginEnd: 10},
    labelRow: {flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 2},
    dot: {width: 5, height: 5, borderRadius: 3, backgroundColor: themeColors.tertiary},
    label: {fontSize: 11, fontWeight: '600', letterSpacing: 0.4, color: themeColors.onSurfaceVariant},
    name: {fontSize: 18, fontWeight: '700', letterSpacing: -0.3, color: themeColors.onSurface, marginBottom: 6},
    specsRow: {flexDirection: 'row', gap: 6, flexWrap: 'wrap'},
    specChip: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 8,
        backgroundColor: themeColors.surfaceContainerLow,
        borderWidth: 1,
        borderColor: themeColors.outlineVariant,
    },
    specText: {fontSize: 11, fontWeight: '600', color: themeColors.onSurfaceVariant},
    manageBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingHorizontal: 12,
        paddingVertical: 9,
        borderRadius: 12,
        backgroundColor: themeColors.tertiary,
    },
    manageBtnPressed: {opacity: 0.85, transform: [{scale: 0.96}]},
    manageBtnText: {fontSize: 12, fontWeight: '700', color: themeColors.onTertiary, letterSpacing: 0.2},
    manageCountChip: {
        marginStart: 2,
        paddingHorizontal: 5,
        paddingVertical: 1,
        borderRadius: 999,
        backgroundColor: themeColors.onTertiary,
    },
    manageCountText: {fontSize: 9.5, fontWeight: '800', color: themeColors.tertiary, letterSpacing: 0.2},
    footer: {
        marginTop: 14,
        paddingTop: 10,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: themeColors.outlineVariant,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    footerText: {fontSize: 11.5, fontWeight: '500', color: themeColors.onSurfaceVariant, flex: 1},
})
