/**
 * Comprehensive car models database organized by manufacturer
 * Includes both current and historical models to support vehicles from 1980 to present
 */

export const CAR_MODELS: Record<string, string[]> = {
    // Japanese Manufacturers
    Toyota: [
        '4Runner',
        '86',
        'Avalon',
        'Aygo',
        'C-HR',
        'Camry',
        'Corolla',
        'Corolla Cross',
        'FJ Cruiser',
        'GR86',
        'GR Corolla',
        'GR Supra',
        'Highlander',
        'Land Cruiser',
        'Mirai',
        'Prius',
        'RAV4',
        'Sequoia',
        'Sienna',
        'Supra',
        'Tacoma',
        'Tundra',
        'Venza',
        'Yaris',
        'Yaris Cross',
    ],
    Honda: [
        'Accord',
        'Civic',
        'Clarity',
        'CR-V',
        'e:NY1',
        'Fit',
        'HR-V',
        'Insight',
        'Odyssey',
        'Passport',
        'Pilot',
        'Ridgeline',
        'ZR-V',
    ],
    Nissan: [
        '370Z',
        'Altima',
        'Armada',
        'Frontier',
        'GT-R',
        'Kicks',
        'Leaf',
        'Maxima',
        'Murano',
        'Pathfinder',
        'Rogue',
        'Sentra',
        'Titan',
        'Versa',
        'Z',
    ],
    Mazda: ['CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-9', 'CX-90', 'Mazda2', 'Mazda3', 'Mazda6', 'MX-5 Miata', 'MX-30'],
    Subaru: ['Ascent', 'BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Legacy', 'Outback', 'Solterra', 'WRX'],
    Mitsubishi: ['Eclipse Cross', 'Mirage', 'Outlander', 'Outlander Sport', 'RVR'],
    Lexus: ['CT', 'ES', 'GS', 'GX', 'IS', 'LC', 'LS', 'LX', 'NX', 'RC', 'RX', 'RZ', 'UX'],
    Acura: ['ILX', 'Integra', 'MDX', 'NSX', 'RDX', 'TLX', 'ZDX'],
    Infiniti: ['Q50', 'Q60', 'QX50', 'QX55', 'QX60', 'QX80'],
    Suzuki: ['Swift', 'Vitara', 'SX4', 'Grand Vitara', 'Jimny', 'S-Cross'],
    Isuzu: ['D-Max', 'MU-X'],

    // American Manufacturers
    Ford: [
        'Bronco',
        'Bronco Sport',
        'EcoSport',
        'Edge',
        'Escape',
        'Expedition',
        'Explorer',
        'F-150',
        'F-250',
        'F-350',
        'F-450',
        'Focus',
        'Fusion',
        'Maverick',
        'Mustang',
        'Mustang Mach-E',
        'Ranger',
        'Super Duty',
        'Transit',
        'Transit Connect',
    ],
    Chevrolet: [
        'Blazer',
        'Bolt EUV',
        'Bolt EV',
        'Camaro',
        'Colorado',
        'Corvette',
        'Cruze',
        'Equinox',
        'Impala',
        'Malibu',
        'Silverado',
        'Sonic',
        'Spark',
        'Suburban',
        'Tahoe',
        'Trailblazer',
        'Traverse',
        'Trax',
    ],
    Dodge: ['Challenger', 'Charger', 'Durango', 'Journey', 'Dart', 'Grand Caravan', 'Viper'],
    Jeep: ['Cherokee', 'Compass', 'Gladiator', 'Grand Cherokee', 'Grand Wagoneer', 'Renegade', 'Wagoneer', 'Wrangler'],
    Ram: ['1500', '1500 Classic', '2500', '3500', '4500', '5500', 'ProMaster', 'ProMaster Cargo Van', 'ProMaster City'],
    Cadillac: [
        'CT4',
        'CT4-V',
        'CT4-V Blackwing',
        'CT5',
        'CT5-V',
        'CT5-V Blackwing',
        'Celestiq',
        'Escalade',
        'Escalade ESV',
        'Lyriq',
        'XT4',
        'XT5',
        'XT6',
        'XTS',
    ],
    GMC: ['Acadia', 'Canyon', 'Hummer EV', 'Savana', 'Sierra', 'Terrain', 'Yukon', 'Yukon XL'],
    Buick: ['Enclave', 'Encore', 'Encore GX', 'Envision', 'LaCrosse', 'Regal'],
    Chrysler: ['300', 'Pacifica', 'Pacifica Hybrid', 'Voyager'],
    Lincoln: ['Aviator', 'Corsair', 'Navigator', 'Navigator L', 'Nautilus'],
    Tesla: ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck', 'Roadster'],

    // German Manufacturers
    BMW: [
        '2 Series',
        '3 Series',
        '4 Series',
        '5 Series',
        '7 Series',
        '8 Series',
        'i3',
        'i4',
        'i5',
        'i7',
        'i8',
        'iX',
        'X1',
        'X2',
        'X3',
        'X4',
        'X5',
        'X6',
        'X7',
        'XM',
        'Z4',
    ],
    'Mercedes-Benz': [
        'A-Class',
        'B-Class',
        'C-Class',
        'CLA',
        'CLS',
        'E-Class',
        'E-Class Coupe',
        'E-Class Cabriolet',
        'EQE',
        'EQS',
        'EQB',
        'EQC',
        'G-Class',
        'GLA',
        'GLB',
        'GLC',
        'GLE',
        'GLS',
        'S-Class',
        'SL',
        'SLC',
        'AMG GT',
    ],
    Audi: [
        'A3',
        'A4',
        'A5',
        'A6',
        'A7',
        'A8',
        'e-tron',
        'e-tron GT',
        'Q3',
        'Q4 e-tron',
        'Q5',
        'Q7',
        'Q8',
        'Q8 e-tron',
        'R8',
        'RS 3',
        'RS 4',
        'RS 5',
        'RS 6',
        'RS 7',
        'RS Q8',
        'S3',
        'S4',
        'S5',
        'S6',
        'S7',
        'S8',
        'TT',
    ],
    Volkswagen: [
        'Arteon',
        'Atlas',
        'Atlas Cross Sport',
        'Golf',
        'GTI',
        'ID.4',
        'ID. Buzz',
        'Jetta',
        'Passat',
        'Polo',
        'Taos',
        'Tiguan',
        'Touareg',
    ],
    Porsche: ['718 Boxster', '718 Cayman', '911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],

    // Other European Manufacturers
    Volvo: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'C40'],
    Jaguar: ['E-PACE', 'F-PACE', 'F-Type', 'I-PACE', 'XE', 'XF', 'XJ'],
    'Land Rover': [
        'Defender',
        'Discovery',
        'Discovery Sport',
        'Range Rover',
        'Range Rover Evoque',
        'Range Rover Sport',
        'Range Rover Velar',
    ],
    Mini: ['Cooper', 'Cooper Clubman', 'Cooper Countryman', 'Cooper Convertible', 'Cooper S', 'John Cooper Works'],
    Fiat: ['124 Spider', '500', '500L', '500X', 'Ducato', 'Panda', 'Tipo'],
    'Alfa Romeo': ['4C', 'Giulia', 'Stelvio', 'Tonale'],
    Peugeot: ['2008', '208', '3008', '308', '5008', '508', 'Rifter', 'Traveller'],
    Renault: ['Captur', 'Clio', 'Kadjar', 'Koleos', 'Megane', 'Scenic', 'Talisman', 'Zoe'],
    Citroen: ['C3', 'C4', 'C5', 'Berlingo', 'C4 Cactus'],
    Saab: ['9-3', '9-5', '9-7X'],

    // Korean Manufacturers
    Hyundai: [
        'Accent',
        'Elantra',
        'Ioniq',
        'Ioniq 5',
        'Ioniq 6',
        'Kona',
        'Palisade',
        'Santa Cruz',
        'Santa Fe',
        'Sonata',
        'Tucson',
        'Venue',
    ],
    Kia: ['Carnival', 'EV6', 'Forte', 'K5', 'Niro', 'Rio', 'Seltos', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Telluride'],
    Genesis: ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],

    // Chinese/Other Manufacturers
    MG: ['HS', 'MG3', 'MG5', 'ZS', 'MG4'],
    BYD: ['Atto 3', 'Dolphin', 'Han', 'Seal', 'Tang', 'Yuan Plus'],
    Geely: ['Coolray', 'Emgrand', 'Tugella'],
    'Great Wall': ['Haval H6', 'Haval Jolion', 'Cannon'],
}
