import type {Part} from '@/shared/types'

/**
 * Sample parts data for testing/demo purposes
 * In a real app, this would come from an API
 */
export const SAMPLE_PARTS: Part[] = [
    // Engine parts
    {
        id: 'part_1',
        name: 'فلتر زيت المحرك',
        description: 'فلتر زيت محرك عالي الجودة لحماية مثالية للمحرك',
        category: 'engine',
        price: 12.99,
        brand: 'ACDelco',
        sku: 'OIL-FILTER-001',
        inStock: true,
        compatibleVehicles: [
            {make: 'Toyota', model: 'Camry', yearFrom: 2015, yearTo: 2023},
            {make: 'Toyota', model: 'Corolla', yearFrom: 2014, yearTo: 2024},
        ],
    },
    {
        id: 'part_2',
        name: 'طقم بواجي (4 قطع)',
        description: 'بواجي إيريديوم لتحسين كفاءة الوقود والأداء',
        category: 'engine',
        price: 45.99,
        brand: 'NGK',
        sku: 'SPARK-4PK-001',
        inStock: true,
        compatibleVehicles: [
            {make: 'Honda', model: 'Civic', yearFrom: 2016, yearTo: 2023},
            {make: 'Honda', model: 'Accord', yearFrom: 2018, yearTo: 2024},
        ],
    },
    {
        id: 'part_3',
        name: 'سير التيمن',
        description: 'سير تيمن بجودة أصلية مع شد مثالي',
        category: 'engine',
        price: 89.99,
        brand: 'Gates',
        sku: 'TIMING-BELT-001',
        inStock: true,
        compatibleVehicles: [{make: 'Toyota', model: 'Camry', yearFrom: 2015, yearTo: 2020, engine: '2.5L'}],
    },
    // Brakes
    {
        id: 'part_4',
        name: 'طقم فحمات فرامل (أمامي)',
        description: 'فحمات فرامل سيراميك ممتازة لفرملة ناعمة وهادئة',
        category: 'brakes',
        price: 65.99,
        brand: 'PowerStop',
        sku: 'BRAKE-PAD-F-001',
        inStock: true,
        compatibleVehicles: [
            {make: 'Ford', model: 'F-150', yearFrom: 2015, yearTo: 2023},
            {make: 'Chevrolet', model: 'Silverado', yearFrom: 2014, yearTo: 2022},
        ],
    },
    {
        id: 'part_5',
        name: 'ديسكات فرامل (زوج أمامي)',
        description: 'ديسكات فرامل مخرمة ومشققة لتحسين أداء الفرامل',
        category: 'brakes',
        price: 129.99,
        brand: 'PowerStop',
        sku: 'ROTOR-F-PAIR-001',
        inStock: true,
        compatibleVehicles: [{make: 'Ford', model: 'F-150', yearFrom: 2015, yearTo: 2023}],
    },
    // Suspension
    {
        id: 'part_6',
        name: 'مساعد أمامي كامل',
        description: 'مساعد كامل مع ياي',
        category: 'suspension',
        price: 189.99,
        brand: 'Monroe',
        sku: 'STRUT-F-001',
        inStock: true,
        compatibleVehicles: [{make: 'Honda', model: 'Civic', yearFrom: 2016, yearTo: 2021}],
    },
    {
        id: 'part_7',
        name: 'مساعد خلفي',
        description: 'مساعد خلفي شديد التحمل لراحة أفضل أثناء القيادة',
        category: 'suspension',
        price: 79.99,
        brand: 'Monroe',
        sku: 'SHOCK-R-001',
        inStock: false,
        compatibleVehicles: [{make: 'Toyota', model: 'Camry', yearFrom: 2015, yearTo: 2023}],
    },
    // Electrical
    {
        id: 'part_8',
        name: 'بطارية سيارة 12 فولت',
        description: 'بطارية AGM لا تحتاج لصيانة مع ضمان 3 سنوات',
        category: 'electrical',
        price: 149.99,
        brand: 'Optima',
        sku: 'BATTERY-12V-001',
        inStock: true,
        compatibleVehicles: [
            {make: 'BMW', model: '3 Series', yearFrom: 2012, yearTo: 2018},
            {make: 'Mercedes-Benz', model: 'C-Class', yearFrom: 2014, yearTo: 2020},
        ],
    },
    {
        id: 'part_9',
        name: 'لمبة شمعة (H7)',
        description: 'لمبة شمعة LED ساطعة، ضوء أبيض 6000K',
        category: 'electrical',
        price: 34.99,
        brand: 'Philips',
        sku: 'BULB-H7-LED',
        inStock: true,
        compatibleVehicles: [
            {make: 'Volkswagen', model: 'Jetta', yearFrom: 2015, yearTo: 2022},
            {make: 'Audi', model: 'A4', yearFrom: 2016, yearTo: 2023},
        ],
    },
    // Body
    {
        id: 'part_10',
        name: 'غطاء صدام أمامي',
        description: 'غطاء صدام أمامي بنمط الأصلي، غير مصبوغ',
        category: 'body',
        price: 299.99,
        brand: 'OEM Plus',
        sku: 'BUMPER-F-001',
        inStock: true,
        compatibleVehicles: [{make: 'Honda', model: 'Civic', yearFrom: 2016, yearTo: 2021}],
    },
    // Interior
    {
        id: 'part_11',
        name: 'طقم دعاسات (4 قطع)',
        description: 'دعاسات مطاطية لجميع الأحوال الجوية، تفصيل خاص',
        category: 'interior',
        price: 89.99,
        brand: 'WeatherTech',
        sku: 'MATS-4PC-001',
        inStock: true,
        compatibleVehicles: [
            {make: 'Toyota', model: 'RAV4', yearFrom: 2019, yearTo: 2024},
            {make: 'Subaru', model: 'Outback', yearFrom: 2020, yearTo: 2024},
        ],
    },
    // Exhaust
    {
        id: 'part_12',
        name: 'دبة تلوث (محول حفاز)',
        description: 'بديل أصلي لدبة التلوث، متوافق مع معايير EPA',
        category: 'exhaust',
        price: 459.99,
        brand: 'Bosch',
        sku: 'CAT-CONV-001',
        inStock: true,
        compatibleVehicles: [{make: 'Toyota', model: 'Camry', yearFrom: 2015, yearTo: 2023, engine: '2.5L'}],
    },
    // Cooling
    {
        id: 'part_13',
        name: 'رديتر',
        description: 'رديتر ألمنيوم لتحسين كفاءة التبريد',
        category: 'cooling',
        price: 199.99,
        brand: 'Mishimoto',
        sku: 'RADIATOR-001',
        inStock: true,
        compatibleVehicles: [{make: 'Ford', model: 'Mustang', yearFrom: 2015, yearTo: 2023}],
    },
    // Transmission
    {
        id: 'part_14',
        name: 'طقم فلتر ناقل الحركة',
        description: 'طقم فلتر ووجه ناقل حركة كامل',
        category: 'transmission',
        price: 39.99,
        brand: 'WIX',
        sku: 'TRANS-FILTER-001',
        inStock: true,
        compatibleVehicles: [{make: 'Chevrolet', model: 'Silverado', yearFrom: 2014, yearTo: 2018}],
    },
    // Fuel
    {
        id: 'part_15',
        name: 'طقم مضخة الوقود',
        description: 'مضخة وقود كهربائية مع فلتر مدمج',
        category: 'fuel',
        price: 189.99,
        brand: 'Bosch',
        sku: 'FUEL-PUMP-001',
        inStock: true,
        compatibleVehicles: [{make: 'Honda', model: 'Accord', yearFrom: 2013, yearTo: 2017}],
    },
    // Tires
    {
        id: 'part_16',
        name: 'طقم إطارات لكل الفصول (4 قطع)',
        description: 'إطار ممتاز لجميع الفصول، 225/65R17',
        category: 'tires',
        price: 599.99,
        brand: 'Michelin',
        sku: 'TIRE-4PK-001',
        inStock: true,
        compatibleVehicles: [{make: 'Subaru', model: 'Outback', yearFrom: 2020, yearTo: 2024}],
    },
]
